site_name: WeatherKit Documentation
site_url: https://suvanbanerjee.github.io/WeatherKit
nav:
  - Home: index.md
  - "Getting Started": getting-started.md
  - "Usage": usage.md
  - "Contribute": contribute.md
theme: readthedocs