site_name: WeatherKit Documentation
site_url: https://suvanbanerjee.github.io/WeatherKit
nav:
  - Home: index.md
  - "Getting Started": getting-started.md
  - "User Guide": user-guide.md
  - "Developer Guide": developer-guide.md
  - "Contribute": contribute.md
theme: readthedocs